woorifisa-projects-3rd/Quostomize-FE

- app/(nav)/layout.jsx
- app/(nav)/test/page.jsx
- components/NavigationBar/bottomNav.jsx
- components/overlay/alertModal.jsx
- components/overlay/bottomDrawer.jsx
- package.json
- pnpm-lock.yaml
Design/Modal : modal, Drawer 예시 추가
> Design/Modal : modal, Drawer 예시 추가

- app/(nav)/home/home-header.jsx
- app/(nav)/home/page.jsx
> 홈: 홈화면 Header

- app/(nav)/home/home-header.jsx
- app/(nav)/home/page.jsx
HomeHeader 기본 구조 구현
-  "{ }" 룰렛 형식처럼 서비스가 돌아가다가 정지(선택)
> 홈: 홈화면 HomeHeader 프레임 구현

- app/(nav)/home/home-body1.jsx
- app/(nav)/home/home-header.jsx
- app/(nav)/home/page.jsx
- package-lock.json
- package.json
오직 나만을 위한 ~ 커스터마이징 문구 추가 - fadein 효과만 적용
> 홈: 홈화면 Body1

- app/(nav)/lotto/page.jsx
- app/(nav)/test/page.jsx
- app/api/test/route.js
- utils/fetch/fet.js
오직 나만을 위한 ~ 커스터마이징 문구 추가 - fadein 효과만 적용
> 홈: 홈화면 HomeBody1 프레임 구현

- app/(nav)/home/home-body1.jsx
- app/(nav)/home/home-body2.jsx
- app/(nav)/home/home-header.jsx
- app/(nav)/home/page.jsx
- components/button/arrow.jsx
- package-lock.json
- package.json
문구: 내가 채워가는 나를 위한 카드
카드 이미지 대체 하여 색상으로 프레임만 구현
> 홈: 홈화면 Body2

- app/(fullscreen)/layout.jsx
- app/(nav)/layout.jsx
- app/globals.css
- components/box/benefit-box.jsx
- components/box/noitce-toggle-box.jsx
- components/box/point-box.jsx
- components/fade-in/fade-in-section.jsx
- components/home/home-body1.jsx
- components/home/home-body2.jsx
- components/home/home-body3.jsx
- components/home/home-body4.jsx
- components/home/home-foot.jsx
- components/home/home-header.jsx
-  fade-in-section components 분리 및 HomeHeader제외, fade-in 효과 적용
- 글자색상 통일 및 글자색상 적용 방식 통일
- globals.css font, color 정의
> 홈: 홈화면 refactoring V3

- app/(fullscreen)/card-benefit-details/page.jsx
- components/cardBenefitDetails/benefit-graph-v1.jsx
- components/cardBenefitDetails/benefit-graph-v2.jsx
- package-lock.json
- package.json
- pnpm-lock.yaml
- 데이터 및 색상
```
const chartDataVersions = [
{
labels: [''],
datasets: [
{
label: '쇼핑',
data: [20],
backgroundColor: '#a8e1ff',
},
{
label: '생활',
data: [20],
backgroundColor: '#88c5ff',
},
{
label: '푸드',
data: [20],
backgroundColor: '#67a9ff'
},
{
label: '여행',
data: [20],
backgroundColor: '#438ff6',
},
{
label: '문화',
data: [20],
backgroundColor: '#0075d9',
},
],
},
{
labels: [''],
datasets: [
{
label: '쇼핑',
data: [20],
backgroundColor: '#a8e1ff',
},
{
label: '생활',
data: [50],
backgroundColor: '#88c5ff',
},
{
label: '여행',
data: [30],
backgroundColor: '#438ff6',
},
],
},
{
labels: [''],
datasets: [
{
label: '쇼핑',
data: [15],
backgroundColor: '#a8e1ff',
},
{
label: '푸드',
data: [40],
backgroundColor: '#67a9ff'
},
{
label: '여행',
data: [15],
backgroundColor: '#438ff6',
},
{
label: '문화',
data: …
```
> 카드상세혜택: 혜택률 그래프

- app/(fullscreen)/layout.jsx
- app/(nav)/layout.jsx
- app/globals.css
- components/home/home-body1.jsx
- components/home/home-body2.jsx
- components/home/home-body3.jsx
- components/home/home-body4.jsx
- components/home/home-header.jsx
Refactor/home layout overflow 추가 및 global.css 색상 및 폰트 추가
> 홈: 홈화면 refactoring V4

- app/(fullscreen)/card-benefit-details/page.jsx
- components/box/brand-box.jsx
- components/cardBenefitDetails/benefit-body2.jsx
> 카드상세혜택: 가맹점 안내

- app/(fullscreen)/card-benefit-details/page.jsx
- components/cardBenefitDetails/benefit-graph-v1-colorchange.jsx
> 카드상세혜택: 혜택그래프 update

- app/(fullscreen)/card-benefit-details/page.jsx
- app/(fullscreen)/login/page.jsx
- components/box/tab-content-box.jsx
- components/cardBenefitDetails/benefit-body1.jsx
- 쇼핑, 생활, 푸드, 여행, 문화 기본 및 상세 안내문구 작성
> 카드상세혜택: 혜택 상세 안내 update

- app/(fullscreen)/create-card/page.jsx
- components/create-card/select-design/select-design3.jsx
> 카드생성: 카드디자인 선택3

- components/create-card/select-design/select-design1.jsx
> 카드생성: 카드디자인 선택1-update

- components/create-card/select-benefit/InteractiveTabContentBox.jsx
- components/create-card/select-benefit/layout.jsx
포인트 적립 상세혜택 선택 옵션에 따라 select-benefit3의 명시
> 카드생성: refactoring V3

- components/create-card/select-benefit/BenefitContext.jsx
- components/create-card/select-benefit/InteractiveTabContentBox.jsx
- components/create-card/select-benefit/select-benefit3.jsx
- components/create-card/select-point/select-point2.jsx
- components/overlay/toast.jsx
- tailwind.config.js
1. 포인트 적립 옵션 선택 페이지 refactoring
2. tailwind.config.js extend값 초기화
> 카드생성: refactoring V4

- app/(fullscreen)/card-benefit-details/page.jsx
> 혜택변경: 혜택변경 Foot - 상위 브랜치 update

- components/piece-stock/favorite/bottom.jsx
- components/piece-stock/search/bottom.jsx
…page.jsx - 위시종목추가 이후, 프론트에 나타나는 순위 문제 해결 코드 작성(아예없을떄 신규생성 했을 경우 3위로 시작하는 문제해결 )
> 조각투자/주식 :  종목위시리스트 화면 내 종목 추가 시 발생하는 문제 해결  

- app/(fullscreen)/login/ErrorModal.jsx
- app/(fullscreen)/login/LoginForm.jsx
- app/(fullscreen)/login/LoginLoading.jsx
- app/(fullscreen)/login/page.jsx
- next.config.mjs
- public/icons/icons.jsx
> 로그인: 로그인 페이지 UI 구성

- app/(nav)/my-card/page.jsx
- app/globals.css
- components/box/pointUsageBox.jsx
- components/card/colorInfo.jsx
- components/card/gradientText.jsx
- components/create-card/select-benefit/select-benefit2.jsx
- components/create-card/select-design/select-design1.jsx
1. 컴포넌트 분리
- ColorInfo 및 GradientText 컴포넌트
- 포인트 사용처 토글 버튼 컴포넌트(페이백, 일일복권, 조각투자)
2. 기능 구현
- 카드 정보 조회
- 포인트 사용처 변경
- 페이백, 일일복권, 조각투자 버튼
> 나의카드: 2차 구현 완료

- app/(fullscreen)/create-card/page.jsx
- app/(nav)/benefit-change/page.jsx
- components/box/InteractiveTabContentBox.jsx
- components/change-benefits/ChangeBenefitBody2.jsx
- components/change-benefits/ChangeBenefitFoot.jsx
- components/create-card/select-benefit/select-benefit2.jsx
- components/overlay/SecondAuthModal.jsx
- 상위혜택 일부 선택 불가 이슈 해결 @seonmin5 
- 2차 인증 모달 useEffect 순서 변경 @Kee0304
> 혜택 변경: 혜택 선택 이슈 해결

- app/(nav)/benefit-change/page.jsx
- app/(nav)/my-card/page.jsx
- app/(nav)/qna/[id]/page.jsx
- app/(nav)/qna/page.jsx
- components/create-card/create-card-bottom.jsx
- components/my-card/CardNotFoundModal.jsx
- next.config.mjs
> 리팩토링: 다양한 UI 수정 및 카드 미존재 에러 수정

- app/(nav)/benefit-change/page.jsx
- app/(nav)/my-card/page.jsx
- app/(nav)/qna/[id]/page.jsx
- app/(nav)/qna/page.jsx
- components/create-card/create-card-bottom.jsx
- components/my-card/CardNotFoundModal.jsx
- next.config.mjs
> 리팩토링: 다양한 UI 수정 및 카드 미존재 에러 수정 dev PR

- components/piece-stock/etc/motion.jsx
- components/piece-stock/home/apiMethod/apiList.jsx
1. 종목검색 시 빈 값으로 검색하면 발생하는 에러코드 수정
2. 관심종목 클릭 시 모션 끊기는 부분 수정
> Refactor/StockSwitchSystem: 코드 종목 검색 시 에러부분 수정 및 모션 문제 수정 

- app/(nav)/lotto/page.jsx
- components/card/ParticipantCard.jsx
- components/card/WinnerCard.jsx
- components/lotto/lottoHeader.jsx
- components/lotto/winningModal.jsx
- 로또 페이지 상단 헤더 삭제
- 상단 3d 아이콘 크기 조정
- 참여자 카드 글자 크기 수정
- 그 외 요소 크기 조정
- 쿠키 저장 로직 수정
> Refactor/LottoFE: 로또 페이지 수정

- app/(nav)/my-card/page.jsx
- components/box/pointUsageBox.jsx
- components/home/HomeBody1.jsx
- components/home/HomeBody2.jsx
나의 카드 페이지 - 포인트 사용처 (카드 생성 페이지 컴포넌트 사용하기)
카드 생성 페이지 컴포넌트를 사용하지 않고 기존 toggle 박스에서 UI 수정 후 그대로 적용
> 리팩토링: 페이지 퍼블리싱 V5

- components/overlay/alertModal.jsx
> 리팩토링: 페이지 퍼블리싱 V8

- app/(nav)/benefit-change/page.jsx
- components/overlay/alertModal.jsx
> 리팩토링: 페이지 퍼블리싱 V9

- app/(fullscreen)/create-card/page.jsx
- app/(nav)/benefit-change/page.jsx
- components/box/InteractiveTabContentBox.jsx
- components/change-benefits/ChangeBenefitBody1.jsx
- components/create-card/check-information/CheckInformation.jsx
- components/overlay/SecondAuthModal.jsx
> 리팩토링: 카드생성 오류 해결

- components/signup/checkModal.jsx
- components/signup/checkModal2.jsx
- components/signup/common/exceptionExcute.jsx
- components/signup/firstFromPrint/firstTotalPrint.jsx
- components/signup/secondFormPrint/secondTotalPrint.jsx
- components/signup/signupFirst.jsx
- components/signup/signupSecond.jsx
Refactor/Signup: 입력칸 너비 조정 + 비밀번호 영대문자 요구 주석처리 + 2차바밀번호입력 모달 짤리는 에러 수정
> 회원가입: 입력칸 너비 조정 및 비밀번호 영대문자 요구 주석처리, 2차비밀번호 모달 문제 수정
